apiVersion: 1

datasources:
  - name: Airflow Metadata
    type: postgres
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: airflow
      sslmode: disable
      postgresVersion: 1600
    isDefault: true